language: R
cache: packages
warnings_are_errors: true
sudo: required
addons:
  r_packages:
    packages:
      - knitr
      - rmarkdown
      - ElemStatLearn
      - usethis
      - ggplot2
      - pander
